
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d  # Konfigurasi Nginx
      - .:/var/www  # Mount project Laravel
    ports:
      - "8080:80"  # Arahkan port 8080 ke 80 di dalam container Nginx
    depends_on:
      - app
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network:
